name: Test, Build, and Deploy to VPS

on:
  push:
    branches:
      - main
      - staging

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install -f

      - name: Run unit tests
        run: npm test

      - name: Build app
        run: npm run build

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            if [ "${GITHUB_REF##*/}" = "main" ]; then
              cd /home/sabdahtb/projects/nest-ts
            elif [ "${GITHUB_REF##*/}" = "staging" ]; then
              cd /home/sabdahtb/projects/nest-ts-staging
            else
              echo "Unknown branch. Exiting."
              exit 1
            fi

            git pull origin ${GITHUB_REF##*/}
            docker compose up -d --build
          EOF
