name: Test, Build, and Deploy to VPS

on:
  push:
    branches:
      - main
      - staging

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install -f

      - name: Run unit tests
        run: npm test

      - name: Build app
        run: npm run build

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            BRANCH_NAME="${BRANCH_NAME}"

            if [ "$BRANCH_NAME" = "main" ]; then
              # Use Swarm for main branch
              cd /home/sabdahtb/projects/nest-ts
              git pull origin main
              docker build -t sabdahtb/nestjs-api:latest .
              docker stack deploy -c stack.yml nest-ts  # Deploy with Docker Swarm
            elif [ "$BRANCH_NAME" = "staging" ]; then
              # Use Docker Compose for staging branch
              cd /home/sabdahtb/projects/nest-ts-staging
              git pull origin staging
              docker compose up -d --build  # Deploy with Docker Compose
            else
              echo "Unknown branch: $BRANCH_NAME. Exiting."
              exit 1
            fi
          EOF
